version: "3"
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
  server:
    build: server
    command: npm start
    ports:
      - 4000:4000
    environment:
      - SECRET=secret
      - POSTGRES_URI=postgres://user:pass@db:5432/db
    depends_on:
      - db
  react:
    container_name: nginxreactapp
    build:
      context: .
      dockerfile: client-experimental/Dockerfile
    ports:
      - 80:80
    environment: 
      NODE_ENV: production
